umd-lib/newspaper-batchload

classes/pcdm.py, config.yml, handler/ndnp.py, load.py, test.py
Completely refactored to incorporate work done on plant patents loader, adding pages, files, proxies, collections, and mutliple ordering (reels), general cleanup and reorg.
=> pages, files, proxies, multiple ordering, collections

classes/pcdm.py, handler/ndnp.py, requirements.txt
This fixes the issue with collection names. This was not a patch problem, but rather the correct triple was not being added to the collection graph.
=> LIBFCREPO-132

classes/pcdm.py
This should eliminate the need for running a separate prefix initialization script on the repository.
=> LIBFCREPO-114. Include prefixes in the SPARQL Update queries.

classes/pcdm.py, load.py
Provide post, patch, and head wrapper methods that add the authentication credentials. Also pass the entire config dictionary to the repository constructor.
=> LIBFCREPO-114. Moved Requests code into the Repository class.

classes/pcdm.py
=> LIBFCREPO-114. Fixed capitalization of ORE proxy predicates.

classes/pcdm.py, handler/ndnp.py
This adds articles to ndnp handler and related objects to the pcdm classes.
=> Articles feature

classes/pcdm.py, handler/ndnp.py, test.py
https://issues.umd.edu/browse/LIBHYDRA-42
=> LIBHYDRA-42. Use dcterms instead of dc for title.

handler/ndnp.py
This adds new triples to the objects in the ndnp handler.  Adds some additional namespaces too.
=> add bibo class triples and other additions to metadata

classes/pcdm.py, load.py
All of the methods in the pcdm classes that issue requests to the repositories now raise a pcdm.RESTAPIException if they do not get a success response from the repository. The item loading in load.py is wrapped in two levels of exception handler. The inner layer catches errors in particular items or components and attempts to rollback that particular item's transaction. The outer layer catches exceptions in creating or rolling back the transactions, and aborts the loader entirely.
=> Use exception handling to catch failed items.

classes/pcdm.py, handler/ndnp.py, load.py, logging.yml
* Add verbose and quiet options that control output level to the console.
* Write a new timestamped logfile for every run of the loader script.
=> Use the logging module for status and debug output.

handler/ndnp.py
Creates new file only when not existing.
Appends correctly to existing files (without duplicating header row on existing files).
Puts reel CSV files in their own directory inside the logs directory for easier loading of those objects later on.
=> handles reel csv file creation more subtly 

handler/reel.py, load.py
With the change to the handler.load fuction, the reel handler no longer had the correct number of parameters.  Also tweaked a couple varialbe names and line breaks.
=> make reel handler work with changes to handler.load function

README.md, create_collection.py
https://issues.umd.edu/browse/LIBFCREPO-241
=> LIBFCREPO-241. Create collection creation tool.

classes/pcdm.py
- adds a PUT method to the repository
- adds a UUID property to the resource class (by splitting off the last part of the URI)
- overrides the create_object method for Proxies such that they are PUT to the URI constructed from the parent component plus the item UUID
=> proxies contained by components

verify_indexing.py
Add the first version of this script to read mapfile and check solr for all item uris, returning a list of unindexed uris.
=> add verify_indexing.py

delete.py
If dryrun is enabled, it just prints the list of URIs that would be deleted, but does not call delete_item on them.
https://issues.umd.edu/browse/LIBFCREPO-304
=> LIBFCREPO-304. Added --dryrun option to delete.py.

classes/pcdm.py, handler/ndnp.py, load.py
* Linked objects is a list of <relationship, object> tuples, where the relationship is an RDF predicate. The only restriction on the object is that it must have a "uri" attribute.
* Added convenience methods to add components, files, etc.
* Objects track their own created status using a "created" attribute.
* Removed old debugging print statement.
=> Moved all linked objects (components, files, etc.) into a single structure.

classes/pcdm.py, delete.py, list.py
Converted "recursive_get" to return a generator that returns (uri, graph) tuples for each object it finds.
https://issues.umd.edu/browse/LIBFCREPO-305
=> LIBFCREPO-305. Include resource title in delete log and list output.

.gitignore, config/templates/batch.yml, handler/ndnp.py
- update gitignore to ignore alternate log dirs (e.g. logs.local, logs.prod)
- update batch config template to include configurable log location and config
- handle missing metadata elements on issue and page
- handle pages with no files (e.g. pages that were published but not available for digitization)
- omit pages with no files from reel object
- break some long lines
=> Handle data problems

load.py
...for cases where XML is missing or cannot be interpreted.
=> make title optional when writing summary data

handler/ndnp.py
Prevents the create_object and update_object methods from attempting to modify the collection resource in the repository. Also moved the code to load the collection form the repository into a class method on the ndnp.Collection class.
https://issues.umd.edu/browse/LIBFCREPO-326
=> LIBFCREPO-326. Set created and updated flags when loading collection from repo.

classes/pcdm.py, create_collection.py, list.py
* create_collection.py: -b/--batch if given will write the collection URI to the given config file; WARNING: this WILL clobber any comments that you have in the batch config file
* list.py: -R/--recursive explicitly list the predicates to walk, instead of defaulting to the PCDM model
Also added some additional namespaces to the pcdm module: ldp, oa, and sc.
=> Additional switches for command line tools.

classes/util.py, extractocr.py, load.py
Created a CompletedLog class that is used by both extractocr.py and load.py to track their already completed items.
https://issues.umd.edu/browse/LIBFCREPO-348
=> LIBFCREPO-348. Maintain an annotated.csv log for extractocr.py.

classes/pcdm.py, handler/ndnp.py
Replace the stream attribute with an open_stream closure that opens the file stream on demand.
https://issues.umd.edu/browse/LIBFCREPO-360
=> LIBFCREPO-360. Open binary streams on demand.

extractocr.py
https://issues.umd.edu/browse/LIBFCREPO-363
=> LIBFCREPO-363. Do transactions per-page instead of per-issue.

delete.py
Use -f/--file to provide a file of URIs to delete. If this option is given, all the URIs in the file are deleted in one transaction.
=> Added delete from file option.

extractocr.py, load.py
Specifies an item log file containing a list of items to ignore.
https://issues.umd.edu/browse/LIBFCREPO-406
=> LIBFCREPO-406. Added --ignore/-i argument.

load.py
Allows a wait time between items (in seconds) to be specified with the "-w, --wait" flag
=> implement wait parameter

load.py
https://issues.umd.edu/browse/LIBFCREPO-389
=> LIBFCREPO-389. --nobinaries implies --noannotations.

classes/ldp.py, classes/oa.py, classes/ore.py, classes/pcdm.py, handler/ndnp.py, handler/reel.py, load.py, namespaces/__init__.py
* Moved the namespace definitions and manager into their own module.
* Alias the namespace in the class as “ns”.
* Separated out the WebAnnotation classes into their own module, and they no longer inherit from pcdm.
* Moved some common core code from pcdm.Resource to ldp.Resource.
* Cleaned up unused imports.
=> Major object model refactoring.

classes/exceptions.py, classes/ldp.py, classes/pcdm.py, create_collection.py, delete.py, extractocr.py, handler/ndnp.py, handler/reel.py, load.py
Moved all exception classes into a class.exceptions module.
https://issues.umd.edu/browse/LIBFCREPO-422
=> LIBFCREPO-422. Create exceptions module.

config/templates/correspondence.yml, handler/correspondence.py
add the KAP (correspondence) handler and a sample config
=> add correspondence handler

classes/util.py, delete.py, list.py, namespaces/__init__.py
They now use the same namespace library as load.py.
https://issues.umd.edu/browse/LIBFCREPO-468
=> LIBFCREPO-468. Fixed list.py and delete.py.

handler/correspondence.py
https://issues.umd.edu/browse/LIBFCREPO-477
=> LIBFCREPO-477. Include page number as fabio:hasSequenceIdentifier.
