umd-lib/newspaper-batchload

- handler/ndnp.py
- load.py
Add a --limit parameter that limits the number of items to ingest. Default if not given is to ingest all items.
Also skip any items where the NDNP handler cannot find the per-issue XML file.
> LIBFCREPO-114. Skip missing and limit number ingested.

- classes/pcdm.py
* Added client certificate authentication that takes precedence over username and password authentication. Set the CLIENT_CERT and CLIENT_KEY values in the config file and Requests will use those files as the request certificate and key.
* For testing on repos with self-signed certificates (e.g., fcrepo-vagrant), added a SERVER_CERT config option to specify the server cert for Requests to trust when making HTTPS connections to the repository.
> LIBFCREPO-114. Client and server certs.

- classes/pcdm.py
- load.py
Added method to test the repository connection. Added a "--ping" command line option that only tests the connection then immediately exits.
If the connection to repo cannot be made (by making a HEAD request to the endpoint), the load.py script exits with a non-zero status.
> LIBFCREPO-114. Test the repo connection.

- classes/pcdm.py
- handler/ndnp.py
Also include the RDF and PCDM namespaces/prefixes in the NDNP namespace manager. This solves an issue where the NDNP graphs were not outputting the proper PREFIX preamble to the update statement.
> Abbreviate URI objects in the triple output using the known prefixes.

- classes/pcdm.py
- handler/ndnp.py
- load.py
- respects the limit on objects set with the -l flag, not only during load, but also during preprocessing phase, which makes testing with small subsets of large batches much more efficient
- adds a creation timestamp to the mapfile for each item loaded
- passes the full set of args (rather than just the path) to the main batch load function, so all args are available when constructing the batch (necessary in particular so the limit would be available during preprocessing)
- refines the wording in a few comments
> respect limit flag during preprocessing

- handler/ndnp.py
- load.py
- adds the path attribute to the reel object (absolute local path to the reel XML), which allows the script to process batches that have been limited using the --limit flag
- checks if the limit is not none before comparing it to number of resources preprocessed to avoid error when comparing Nonetype to integer in cases where the limit is unset
> fix bug with empty limit and missing reel path attribute

- classes/pcdm.py
- load.py
Specify an RDF file (Turtle, RDF/XML, or N-Triples format) using the "--extra" or "-x" command line options to include those triples in every top-level item loaded by the loader. Use "<>" in the graph to specify the item.
https://issues.umd.edu/browse/LIBFCREPO-214
> LIBFCREPO-214. Added "--extra" option.

- handler/ndnp.py
The Solr index and Archelon are expecting the display title to be in dcterms:title instead of dc:title.
> Use dcterms:title for article titles.

- handler/ndnp.py
- load.py
Converts the batch object to an iterator, with a \_\_next\_\_() method under which issues are created. This allows object creation to be limited to the issue, pages, files, and articles associated with a particular item.
The changes to load.py are primarily to provide clearer comments for the user.
> convert batch object to iterator to allow streaming

- handler/ndnp.py
Fixes LIBFCREPO-229, to record the pixel dimensions of master TIF files. Uses the predicate ebucore:height/width for now (can be adjusted before load to production if a better fit can be found).
> record pixel dimensions

- classes/pcdm.py
- handler/ndnp.py
- load.py
This PR resolves part of LIBFCREPO-226:  it deals with batches containing multiple reels.
It does not yet handle reel creation for interrupted batches, since it works by keeping the pages created for the issues in memory until it is time to create the reel.
A further improvement would be to read page URIs for previously created items out of the mapfile and add those pages to the reel object.  This would allow reels to be created even when the batch had been interrupted.
> handle multiple reels

- classes/pcdm.py
- load.py
* Moved the checksumming and MIME type analysis into the create_nonrdf method, so that any FileNotFoundErrors raised by the sha() method will get caught by the exception handler in load_item
* Added FileNotFoundError to the load_item exception handler
* Check for whether load_item succeeded before writing to the mapfile for the current item
> Handle FileNotFoundErrors raised when uploading binaries.

- classes/pcdm.py
- handler/ndnp.py
- handler/reel.py
- Changes the relations between issues and articles to pcdm:hasMember as opposed to pcdm:hasRelatedObject.
- Distinguishes between ordered and unordered members so proxies are not created for the latter.
- Removes the reel class from the ndnp handler since reels are now created in a separate handler.
- Provides clearer logging by pulling the title of the specified collection from Fedora and using that in log messages.
- Breaks some long lines according to Python convention.
> Article members

- handler/reel.py
frame number is now stored under ndnp:sequence predicate so the reel handler needs to create proxies and order them using those values
> fix bug in proxy creation for reels

- classes/pcdm.py
- handler/ndnp.py
- load.py
- creates a post_creation_hook method to use for cleanup and other tasks after an item commit
- fixes the print_item_tree method to work with unordered components
- removes the old create_object method that wrote to the CSV during page creation
> Post trans

- handler/ndnp.py
- load.py
- creates a skipped.csv to record files that could not be loaded
- moves a lot of initial data loading out of the init() and into a read_data() method for the issue, in order that it can be wrapped in an exception handler
- creates an exception class for data reading errors
NOTE: There are a few print statements that remained behind after some debugging (in ndnp.Issue.init() and ndnp.batch.next() which may need to be taken out or converted to logging messages
> Data read error handler

- classes/pcdm.py
Omits adding the pcdm:hasMember predicate to the owning collection when creating PCDM objects. This should improve performance by avoiding one source of many-membered objects.
With this change committed, any Solr queries looking for collection membership will need to rely on the "[issue] pcdm:memberOf [collection]" relationship instead. Relationships between objects or between objects and files are still two-way relationships.
> make collection membership a one-way relationship

- classes/pcdm.py
because collection creation is now a separate process, and also collections no longer point to members, it is not necessary for the loader to be touching the collection object in Fedora at all
> suppress unnecessary updates to collection object

- classes/pcdm.py
- handler/ndnp.py
Added as related objects of class fabio:Metadata, which then each have one pcdm:File of the actual XML. These files are represented by the class ndnp.MetadataFile, which adds fabio:MetadataDocument to their list of RDF types.
Also changed the pcdm.File constructor to take an optional title argument and use that (or the basename of the filepath) to set the dcterms:title in the file's metadata. This ensures that every pcdm:File has a title, not just ones that are created via the ndnp.File class.
https://issues.umd.edu/browse/LIBFCREPO-269
> LIBFCREPO-269. Add the METS metadata files to the issue.

- handler/ndnp.py
Deals with the exception raised by an issue missing metadata -- while some issues could probably be loaded without certain metadata being present, it is better to catch this exception, set the issue aside for later examination, and move on.
> handle exception raised by missing data in issue XML

- classes/pcdm.py
- create_collection.py
- handler/ndnp.py
- load.py
Each PCDM object now has a graph() method that constructs the RDF graph from its in-memory metadata. The update_object() method calls graph() just before sending the PATCH request to update the object, so all of the child and related objects should already have URIs in fcrepo. It is now the responsibility of each object to track and add its own relationships to its graph.
Also added "bibo:pageStart" and "bibo:pageEnd" properties to the Article objects.
> Refactor object updating process.

- classes/pcdm.py
- list.py
Uses recursive_get method of the Repository class to walk the objects in the repository and assemble a set of URI strings. The list.py utility reads a list of item URIs on STDIN and prints those URIs plus the URIs of all their components to STDOUT.
https://issues.umd.edu/browse/LIBFCREPO-295
> LIBFCREPO-295. Added utility to list the URIs of all the components of an item.

- classes/pcdm.py
- delete.py
Pass it a comma-separated list of prefixed identifiers to set the predicates for it to traverse when it does a recursive_get. The recognized prefixes are the ones defined in the pcdm module's namespace manager. Full URIs may also be given, but must be written in N3 format like <http://pcdm.org/models#hasFile>
https://issues.umd.edu/browse/LIBFCREPO-290
> LIBFCREPO-290. Add recursive option to delete.py script.

- config/templates/batch.yml
- load.py
- make the log location part of batch configuration
- make the log configuration file path part of batch configuration
- update batch config template
- refactor load.py for consistency and (hopefully) greater clarity
respecting the log location specified in the batch config necessitated changing the order of the processing of configuration files, which in turn led to some refactoring for consistency of variable names and 'de-denting' of some long with/open blocks.
> LIBFCREPO-291

- classes/pcdm.py
Added support for:
* Creating resources with fragment identifiers
* Doing a PUT instead of a POST in the pcdm.Resource.create_object base class
* Temporary override of the repository relpath in a `with repo.at_path('foo')` block
These changes are all in support of modelling the OCR textblocks as Web Annotations. See https://issues.umd.edu/browse/LIBFCREPO-273
> Fragment resources, unified create_object, and relpath overrides

- verify_indexing.py
verify_indexing.py takes a mapfile and compares the files loaded to fcrepo against those found in the solr core, reporting back a list of unindexed items
> verify_indexing.py should respect LOG_LOCATION set by config

- list.py
Without that switch, it only prints the URI so it can be easily piped to the reindex.sh script. With the switch, it also prints the title, for a more human reader-friendly output.
https://issues.umd.edu/browse/LIBFCREPO-325
> LIBFCREPO-325. Added a -l/--long mode to list.py.

- classes/ocr.py
- classes/pcdm.py
- handler/ndnp.py
- load.py
* Include word-level coordinates embedded in the plain text.
* Use Web Annotations structure.
* Use the prov:wasDerivedFrom predicate to connect the oa:TextualBody of the OCR text back to the XML element in the ALO file it was generated from
https://issues.umd.edu/browse/LIBFCREPO-332
> LIBFCREPO-332. Create OCR textblock annotations during load.

- classes/ocr.py
- handler/ndnp.py
Drive the extraction from the page ALTO XML and not the article-level segmentation METS file. This will create text block annotations for all text on the pages, not just the articles. THus it will include mastheads, advertisements, and any other non-article blocks.
https://issues.umd.edu/browse/LIBFCREPO-332
> LIBFCREPO-332. Extract all text blocks from the page.

- classes/pcdm.py
- extractocr.py
- handler/ndnp.py
- load.py
Created extractocr.py script that takes a 1 or more issue URIs and creates web annotations in fcrepo for each OCR textblock in the original ALTO XML files currently stored in fcrepo. Required refactoring of some of the ndnp and pcdm classes to separate the code to parse the METS XML from the constructor, so that objects could be created from the repository instead. Also redesigned pcdm.File class around streams instead of file names. Each issue's annotations are created in a separate transaction. Added "--noannotations" flag to load.py to do a batch load without creating annotations.
https://issues.umd.edu/browse/LIBFCREPO-331
> LIBFCREPO-331. OCR extraction tool.

- classes/util.py
- extractocr.py
- handler/ndnp.py
- load.py
* Will record the skipped item and move on to the next one if there is a non-fatal error while attempting to extract OCR text and create annotations.
* Renamed CompletedLog to ItemLog, and reuse it to also record the skipped items for a run of load.py or extractocr.py. Include the timestamp and program name in the skipped.csv filename.
https://issues.umd.edu/browse/LIBFCREPO-366
> LIBFCREPO-366. Added exception handling to extractocr.py.

- handler/ndnp.py
Skip the parsing, and return an empty list for the textblocks(), for pages that
don't have OCR files.  Catch the StopIterator exception from the call to next(),
and just set the ocr and ocr_file to None.
> Handle missing OCR files.

- handler/ndnp.py
This eliminates the potential KeyErrors for when there are issues missing pages. The pages dictionary was no longer being used by anything in the read_data method.
https://issues.umd.edu/browse/LIBFCREPO-383
> LIBFCREPO-383. Remove unused pages dictionary.

- classes/pcdm.py
- config/logging.yml
- load.py
Use a secondary thread to send a refresh request to the transaction every 90 seconds (half the length of the transaction lifetime of 3 minutes).
https://issues.umd.edu/browse/LIBFCREPO-411
> LIBFCREPO-411. Add a "keep-alive ping" to the transactions.

- classes/pcdm.py
Optional uri parameter to the pcdm.File.create_object() method that triggers a PUT request to that URI instead of the usual POST.
https://issues.umd.edu/browse/LIBFCREPO-409
> LIBFCREPO-409. Allow binary creation at a given URI.

- load.py
Adds "-%, --percent" parameter that allows loading a specified percentage of the batch spread evenly across the whole. This option will provide a more representative test load on dev/stage prior to loading on production.
Supports any percentage from 1-99 by converting the percentage to a ratio of "x out of every y" items. For example, 10% would load 1 of every 10 items, while 75% would load 3 out of every 4. NOTE: Within each subset of items, the items loaded are not necessarily evenly distributed, e.g. loading 60% results in the first three of every 5 items being loaded (= 1, 2, 3, ..., 6, 7, 8, ...etc.), but this distribution should be sufficient for the intended purpose.
> LIBFCREPO-390. Provides percentage parameter for loads.

- classes/pcdm.py
All the other HTTP methods (head, get, post, put, patch, delete) are now thin wrappers around the request method. This means that there will be one place to implement mock requests for dry-run mode.
> Create a generic request method.

- classes/pcdm.py
Avoid having to load the entire binary into memory.
https://issues.umd.edu/browse/LIBFCREPO-413
> LIBFCREPO-413. Use streams for binary POST requests.

- classes/pcdm.py
- handler/ndnp.py
Move the from_repository class method into the pcdm.Collection base class, since it is very generic and useful for things other than the NDNP handler.
https://issues.umd.edu/browse/LIBFCREPO-421
> LIBFCREPO-421. Move from_repository method to pcdm.Collection.

- classes/pcdm.py
- Ensure ordering attribute is respected when generating list of ordered components.
- Also fixes bug in the print_item_tree debugging function
> LIBFCREPO-442

- classes/pcdm.py
Don't call the requests.post() method directly in the pcdm.Repository class. Also added logging to the rollback_transaction() method to match the other transaction methods.
> Use the self.post() wrapper method.
